version: "3.8"

services:
  backend:
    container_name: webhookBackend
    build: ./webhook
    environment:
      - NODE_ENV=production
    ports:
      - "3500:3500"
    restart: always
    volumes:
      - /var/webhook/uploads:/app/uploads
      - ./keywords.txt:/app/keywords.txt

  flask-api:
    build: ./ai
    ports:
      - "5000:5000"
    restart: unless-stopped

# volumes:
#   main_data:
